// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epjcgskawituplnnpiew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwamNnc2thd2l0dXBsbm5waWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDY0MDYsImV4cCI6MjA3MTc4MjQwNn0.5bY3YncK-8DH2RHe0Frwjx8NmzeZA16R7daY90kUinU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});